export const projects = [
  {
    title: 'GTP3 Open AI',
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  ",
      image: '/images/gpt3eli.JPG',
      tags: ['React', 'Node'],
    source: 'https://gpt3eli.netlify.app/#features',
    visit: 'https://github.com/elidallen/Eli-Allen-Mitchell',
    id: 0,
  },
  {
    title: 'Restaurant',
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
    image: '/images/restauranteli.JPG',
    tags: ['React', 'Node'],
    source: 'https://restauranteli.netlify.app/',
    visit: 'https://github.com/elidallen/elirestaurant',
    id: 1,
  },
  {
    title: 'Gym Exercises',
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
      image: '/images/gymeli.JPG',
      tags: ['React', 'Node', 'Material UI', 'Rapid API'],
    source: 'https://gymexerciseseli.netlify.app/',
    visit: 'https://github.com/elidallen/gymeli',
    id: 2,
  },
  {
    title: 'Bank App',
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
    image: '/images/paymentseli.JPG',
    tags: ['React', 'Vite', 'Node', 'Tailwind'],
    source: 'https://bankappeli.netlify.app/',
    visit: 'https://github.com/elidallen/elibank',
    id: 3,
  },
  {
    title: 'Youtube Clone',
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
    image: '/images/youtubeeli.JPG',
    tags: ['React', 'Node', 'Material UI', 'Rapid API'],
    source: 'https://youtubeeli.netlify.app/',
    visit: 'https://github.com/elidallen/youtubeeli',
    id: 4,
  },
];

